### ISSUE TITLE
Spelling error in variable name

### ISSUE THREAD

**Issue by wpyoga** [ZacWolf/WebKiosk#1]
https://github.com/ZacWolf/WebKiosk/blob/69a8086ae66a089e5b506c1b649ebe0f528ff9ab/setupkiosk.sh#L111
https://github.com/ZacWolf/WebKiosk/blob/69a8086ae66a089e5b506c1b649ebe0f528ff9ab/setupkiosk.sh#L146

With this spelling error, ~nothing~ *an empty line* will get written to `.xsession` file.

**Comment by ZacWolf** [comment]
Sorry for the long delay in getting to this. I wasn't monitoring.
Thank you for catching this error!!!  I've made the correction and committed 20201105
